#!/bin/sh
# Pick up newly built dwarfdump in two flavors.
# Pick up libdwarf in two flavors.

# The -fsanitize=address tells gcc to use extra run-time
# code to look for code writing where it should not.
# It should be sufficiently efficient to do by default, but
# we will see.
#  The gcc option is -fsanitize=address and the like
if [ x$NLIZE = 'xy' ]
then
sanitize="--enable-sanitize"
else
sanitize=
fi

set -x
# Fix the following line to match the desired libdwarf/dwarfdump source 
# directory.
. ./BASEFILES

(cd $libdw/libdwarf; ./configure $sanitize  --enable-oldframecol ; make clean ; make  )
cp $libdw/libdwarf/libdwarf.a libdwoldframecol.a
if [ $? -ne 0 ]
then
  echo "No libdwoldframecol.a copied! giving up."
  exit 1;
fi

(cd $libdw/libdwarf; ./configure $sanitize --enable-windowspath; make clean ; make  )
(cd $libdw/dwarfdump ; ./configure $sanitize ; rm dwarfdump ; make clean ; make)
cp $libdw/dwarfdump/dwarfdump   dwarfdumpW
if [ $? -ne 0 ]
then
  echo "No dwarfdumpW done! giving up."
  exit 1;
fi

(cd $libdw/libdwarf;   make clean;  ./configure $sanitize ; make clean ; make )
cp $libdw/libdwarf/libdwarf.a libdwarf.a
if [ $? -ne 0 ]
then
  echo "No libdwarf.a to copy! giving up."
  exit 1;
fi
(cd $libdw/dwarfdump ; make clean ; ./configure $sanitize ; make clean ; make)
(cd $libdw/dwarfgen ; make clean ; ./configure $sanitize ; make clean ; make)
(cd $libdw/dwarfexample ; make clean ; ./configure $sanitize ; make clean ; make)

cp $libdw/dwarfdump/dwarfdump  .
if [ $? -ne 0 ]
then
  echo "No dwarfdump to copy! giving up."
  exit 1;
fi
cp $libdw/dwarfdump/dwarfdump.conf  .
if [ $? -ne 0 ]
then
  echo "No dwarfdump.conf to copy! giving up."
  exit 1;
fi
cp $libdw/libdwarf/gennames .
if [ $? -ne 0 ]
then
  echo "No gennames to copy! giving up."
  exit 1;
fi
cp $libdw/dwarfgen/dwarfgen .
if [ $? -ne 0 ]
then
  echo "No dwarfgen to copy! giving up."
  exit 1;
fi
cp $libdw/dwarfexample/simplereader .
if [ $? -ne 0 ]
then
  echo "No simplereader to copy! giving up."
  exit 1;
fi
