#!/bin/bash

if  [ $# -eq 0 ]
then
    echo supply file with list of objects in a file
    echo which scripts/findobjects will create for you
    exit 1
fi
path=$1

while read n
do
  #echo "do $n"
  /tmp/dwarfdump $n | egrep '(line table version|version_stamp)' >/tmp/junk2
  if [ $? -eq 0 ]
  then
    echo -n  $n " " >/tmp/junk3
    cat /tmp/junk3 /tmp/junk2
  fi
done  < $path

