#!/bin/bash

if  [ $# -eq 0 ]
then
    echo supply file with list of objects in a file
    exit 1
fi
path=$1

while read n
do
  #echo "do $n"
  readelfobj $n | grep '[.]debug_names' >/tmp/junk2
  if [ $? -eq 0 ]
  then
    echo -n  $n " " >/tmp/junk3
    cat /tmp/junk3 /tmp/junk2
  #else
  #  echo "NO such section in $n"
  fi
done  < $path

